#include <stdint.h>

/* Symbols defined in the linker script (memory.ld)   */

/* uint32_t is used because addresses are 32-bit wide */
/* These are not variables — they are linker-generated addresses.             */
/* 'extern' tells the compiler the symbol is resolved later by the linker,    */
/* so no storage is allocated. Always take their ADDRESS with &, never their  */
/* value directly.    */

/* * MISRA-C Deviation Note: 
 * These symbols are generated by the linker (memory.ld). 
 * Using extern declarations here is a necessary deviation to bridge 
 * the Linker and C environments.
 */
extern uint32_t _sidata[];    /* start of .data initializers in Flash (LMA) */
extern uint32_t _sdata[];     /* start of .data section in RAM (VMA)        */
extern uint32_t _edata[];     /* end   of .data section in RAM (VMA)        */
extern uint32_t _sbss[];      /* start of .bss section in RAM               */
extern uint32_t _ebss[];      /* end   of .bss section in RAM               */
extern uint32_t _estack;    /* top of RAM: initial stack pointer value    */

/* Forward declaration of the application entry point */
/* main() is defined in another file; extern makes it callable   */
/* from here without a header file.                              */
extern int main(void) __attribute__((noreturn));

/* Default handler for unused / unimplemented exceptions */
void Default_Handler(void) 
{
    for (;;) { /* MISRA-compliant infinite loop */ }
}

/* Prototypes for the core exception handlers */
void Reset_Handler(void);
/* Weak aliases: if the application does not define its own handler,         */
/* these exceptions fall through to Default_Handler (infinite loop).         */
/* Override by defining a function with the exact same name in any .c file.  */
void NMI_Handler(void)       __attribute__ ((weak, alias ("Default_Handler")));
void HardFault_Handler(void) __attribute__ ((weak, alias ("Default_Handler")));

/* Interrupt vector table */
/* The section attribute places this array at .isr_vector, which the linker  */
/* script maps to the very start of Flash (0x08000000 on STM32).             */
/* The Cortex-M core reads this table on reset to locate the initial stack   */
/* pointer and the Reset_Handler entry point.                                */

/* * MISRA-C Deviation Note: 
 * The Vector Table requires mixing data pointers (Initial SP) and 
 * function pointers (Reset_Handler). This is a hardware-mandated 
 * requirement of the ARM Cortex-M architecture.
 */
__attribute__ ((section(".isr_vector")))
uint32_t *vectors[] = {
    (uint32_t *)&_estack,          /* 0x00: Initial Stack Pointer (top of RAM, 0x2002 0000)  */
    (uint32_t *)Reset_Handler,     /* 0x04: Reset Vector — entry point on boot  */
    (uint32_t *)NMI_Handler,       /* 0x08: Non-Maskable Interrupt              */
    (uint32_t *)HardFault_Handler, /* 0x0C: Hard Fault — catch-all CPU fault    */
    /* Remaining vectors: MemManage, BusFault, UsageFault,                */
    /* SVCall, PendSV, SysTick, and external IRQs (TIM, UART, SPI, ...)   */
};


void Reset_Handler(void)
{
    /* ------------------------------------------------------------------ */
    /* 1. Copy .data section from Flash (LMA) to SRAM (VMA)               */
    /*    _sidata : start of initializer values in Flash                   */
    /*    _sdata  : destination start in RAM                               */
    /*    _edata  : destination end   in RAM                               */
    /* ------------------------------------------------------------------ */

    uint32_t *pSrc = _sidata;  /* read from Flash */
    uint32_t *pDst = _sdata;   /* write to RAM    */

    /* cppcheck-suppress comparePointers */
    /* MISRA Deviation: _sdata and _edata are linker symbols defining 
       the boundaries of the same physical memory block. Comparison 
       is safe within this specific context. */
    while (pDst < _edata)
    {
        /* MISRA: Avoiding side effects in expressions (no *pDst++ = *pSrc++) */
        *pDst = *pSrc;
        pDst++;
        pSrc++;
    }

    /* ------------------------------------------------------------------ */
    /* 2. Zero-fill the .bss section in SRAM                               */
    /*    C standard guarantees uninitialized globals are zero;            */
    /*    no Flash storage is used, so we zero the region at runtime.      */
    /* ------------------------------------------------------------------ */

    pDst = _sbss;

    // cppcheck-suppress comparePointers 
    /* MISRA Deviation: _sbss and _ebss define a single continuous 
       memory region in SRAM. Relational comparison is required 
       for the initialization loop. */
    while (pDst < _ebss)
    {
        *pDst = 0U;
        pDst++;
    }

    /* ------------------------------------------------------------------ */
    /* 3. Hand off to the application                                      */
    /* ------------------------------------------------------------------ */
    main();

    /* main() should never return on embedded targets.                     */
    /* If it does (e.g. during debugging), trap here to avoid undefined    */
    /* behaviour from executing whatever lies after main() in Flash.       */
    for (;;) { }
}
